os: linux
dist: focal
language: python

python:
  - "3.11"

install:
  - sudo apt -y update
  - sudo apt -y install python3-pip zip unzip openjdk-17-jdk git libffi-dev libssl-dev
  - pip3 install --upgrade Cython==0.29.36 virtualenv
  - git clone https://github.com/kivy/buildozer.git
  - cd buildozer && sudo python3 setup.py install && cd ..
  - buildozer android clean  # Очищення перед збіркою

script:
  - yes | buildozer android debug

deploy:
  provider: releases
  edge: true
  token: $GITHUB_TOKEN
  file: bin/*.apk
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
