name: Build Kivy APK

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential git zip unzip \
              openjdk-11-jdk python3-pip python3-setuptools \
              libncurses5 libstdc++6 libffi-dev libssl-dev \
              libsqlite3-dev libjpeg-dev zlib1g-dev
          pip install --upgrade pip Cython virtualenv
          pip install buildozer

      - name: Build APK
        run: |
          cd pymusic
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: pymusic-apk
          path: bin/*.apk

